% displaySequenceInfo.m
function displaySequenceInfo(sequence, sequenceName)
    % Displays information about the DNA sequence
    % Inputs:
    %  - sequence: DNA sequence as a string
    %  - sequenceName: Name or ID for the sequence
    
    % Calculate base counts
    numA = sum(sequence == 'A');
    numT = sum(sequence == 'T');
    numC = sum(sequence == 'C');
    numG = sum(sequence == 'G');
    
    % Total length of the sequence
    totalBases = length(sequence);
    
    % Calculate GC content
    gcContent = ((numG + numC) / totalBases) * 100;
    
    % Create a figure for displaying the information
    fig = uifigure('Name', 'DNA Sequence Information', 'Position', [100, 100, 400, 300]);
    fig.WindowStyle = 'normal';
    
    % Format the information text
    infoText = sprintf(['--- Sequence Information ---\n', ...
                        'Sequence Name: %s\n', ...
                        'Total Bases: %d\n', ...
                        'Base Composition:\n', ...
                        '  A: %d (%.2f%%)\n', ...
                        '  T: %d (%.2f%%)\n', ...
                        '  C: %d (%.2f%%)\n', ...
                        '  G: %d (%.2f%%)\n', ...
                        'GC Content: %.2f%%\n\n', ...
                        '--- Brief Description ---\n', ...
                        'This DNA sequence, named "%s", contains %d bases.\n', ...
                        'It is composed of %.2f%% Guanine (G) and %.2f%% Cytosine (C) bases, indicating a GC-rich content of %.2f%%.\n', ...
                        'A higher GC content can indicate greater stability due to stronger G-C bonds.\n'], ...
                        sequenceName, totalBases, numA, (numA / totalBases) * 100, ...
                        numT, (numT / totalBases) * 100, numC, (numC / totalBases) * 100, ...
                        numG, (numG / totalBases) * 100, gcContent, ...
                        sequenceName, totalBases, (numG / totalBases) * 100, ...
                        (numC / totalBases) * 100, gcContent);
    
    % Create a text label in the figure to display the information
    infoLabel = uilabel(fig);
    infoLabel.Text = infoText;
    infoLabel.FontSize = 12;
    infoLabel.Position = [10 10 380 280]; % Adjust the position and size for readability
    infoLabel.FontName = 'Courier'; % Use a monospaced font for alignment
    
    % Adjust text wrapping if the text goes beyond the figure height
    infoLabel.WordWrap = 'on';
end